version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: salesapp
      MYSQL_USER: salesapp

  django:
    build: .
    image: django
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - ../salesapp:/salesapp
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network
    depends_on:
      - django

networks:
  db_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  db_data:
